replicaCount: 1

image:
  repository: cloudops-cockpit
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 2Gi

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "azure/application-gateway"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
  host: cockpit.internal.cloudapp.azure.com
  path: /
  pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
